### ISSUE TITLE
volumes attached to instances not included

### ISSUE THREAD

**Issue by deconya** [hunter-io/ovh-snapshot#1]
Hi
Script works as expected but instances with volumes attached not appears in instances list. Exist any form to detect volumes? 
Thanks

**Comment by BastienL** [comment]
Hey @deconya,

A solution would be to use `GET /cloud/project/{serviceName}/volume` (https://api.ovh.com/console/#/cloud/project/%7BserviceName%7D/volume#GET) to get the list of volumes and then `POST /cloud/project/{serviceName}/volume/{volumeId}/snapshot` (https://api.ovh.com/console/#/cloud/project/%7BserviceName%7D/volume/%7BvolumeId%7D/snapshot#POST) to snapshot specific volumes.

Would that match your use case?

**Comment by deconya** [comment]
Nice!, Im checking code from first link but produce error how invalid signature. 
Anyway in this case I don't know If we can include in the project this feature because normally If volume is attached to instance you will do snapshots too.

**Comment by BastienL** [comment]
I created a fresh instance and attached a volume to it:

![screen shot 2018-08-03 at 17 46 45](https://user-images.githubusercontent.com/2206060/43652342-408848be-9745-11e8-85b6-1bf798210d46.png)

It is, as expected, part of the instances list:
```
▶ docker run [...] quay.io/hunter-io/ovh-snapshot:0.4 python instances.py
Name                  ID
--------------------  ------------------------------------
test-snapshot         80a3037e-ab75-4f27-9411-xxxxxxxxxx
```

@deconya Can you retry and let me know?
